import { Product } from '@/types'

export const Products: Product[] = [
  {
    _id: '1',
    url: 'https://www.amazon.com/Apple-iPhone-15-Plus-256GB/dp/B0CMT3P49Q',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/51A+nRCJlmL._AC_SX425_.jpg',
    title: 'Apple iPhone 15 Plus, 256GB, Black - Unlocked (Renewed)',
    currentPrice: 864.97,
    originalPrice: 864.97,
    priceHistory: [],
    highestPrice: 864.97,
    lowestPrice: 859,
    averagePrice: 864.97,
    discountRate: 0,
    description:
      '6.7 inch Super Retina XDR display. Aluminum with color-infused glass back. Ring/Silent switch Dynamic Island. A magical way to interact with iPhone. A16 Bionic chip with 5-core GPU Advanced dual-camera system. 48MP Main | Ultra Wide. Super-high-resolution photos (24MP and 48MP). Next-generation portraits with Focus and Depth Control. 4X optical zoom range Emergency SOS via satellite. Crash Detection. Roadside Assistance via satellite Up to 26 hours video playback. USB C, Supports USB 2. Face ID',
    category: 'Cell Phones & Accessories',
    reviewsCount: 29,
    recommendation: 85,
    stars: 4.7,
    isOutOfStock: false
  },
  {
    _id: '2',
    url: 'https://www.amazon.com/Monitor-FreeSync-Premium-Refresh-Support/dp/B0CJQ7V6M8',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/71lKsFn1SHL._AC_SX355_.jpg',
    title:
      'Acer Nitro 23.8" Full HD 1920 x 1080 PC Gaming IPS Monitor | AMD FreeSync Premium | 180Hz Refresh | Up to 0.5ms | HDR10 Support | 99% sRGB | 1 x Display Port 1.2 & 2 x HDMI 2.0 | KG241Y M3biip',
    currentPrice: 119.99,
    originalPrice: 149.99,
    priceHistory: [],
    highestPrice: 155.99,
    lowestPrice: 119.99,
    averagePrice: 149.99,
    discountRate: 20,
    description:
      '23.8" Full HD (1920 x 1080) Widescreen IPS Monitor | AMD FreeSync Premium Technology Refresh Rate: 180Hz | Response Time: 1ms (G to G) - Up to 0.5ms (G to G) | Pixel Pitch: 0.275mm Color Gamut: 99% sRGB | HDR10 Support | Zero-Frame Design VESA mounting compliant (100 x 100mm) | Ergonomic Tilt: -5° to 15° Ports: 1 x Display Port 1.2 and 2 x HDMI 2.0 (HDMI Cable Included)',
    category: 'Computer Monitors',
    reviewsCount: 29,
    recommendation: 76,
    stars: 4.7,
    isOutOfStock: false
  },
  {
    _id: '3',
    url: 'https://www.amazon.in/Bacca-Bucci-Essential-Everyday-Purpose/dp/B0C3XVB8GK',
    currency: '₹',
    image: 'https://m.media-amazon.com/images/I/71fn1hHssYL._SL1500_.jpg',
    title:
      'Bacca Bucci Essential Your Everyday All Purpose Walking Running Casual Shoes',
    currentPrice: 1099,
    originalPrice: 2499,
    priceHistory: [],
    highestPrice: 2499,
    lowestPrice: 1099,
    averagePrice: 2499,
    discountRate: 56,
    description:
      "Total Comfort for Everyday Use: Extra padding at the tongue and collar helps keep your feet feeling comfortable. We also placed engineered mesh—which is stronger and more flexible than regular mesh—throughout the top for lightweight breathability. Supportive Steps: Impactwire technology is integrated with a midfoot band for total support that helps keep your feet in place. Snap, Run, and Pop: This Shoe is more Lightweight than our predecessor, with durable foam that delivers a smooth, responsive ride. We paired it with an outsole unit at the forefoot and the heel for an energized feel. Smooth Transitions: The heel shape is designed to optimize landing, helping you easily transition from heel to toe. We've paired it with thick foam for a responsive ride. More Benefits: The tongue is separated from the upper to give room for different foot shapes. The waffle-inspired outsole gives you excellent traction. Grooves on the rubber sole allow for natural motion.",
    category: 'Shoes',
    reviewsCount: 176,
    stars: 3.9,
    isOutOfStock: false
  },
  {
    _id: '4',
    url: 'https://www.amazon.in/Bacca-Bucci-Essential-Everyday-Purpose/dp/B0C3XVB8GK',
    currency: '₹',
    image: 'https://m.media-amazon.com/images/I/71fn1hHssYL._SL1500_.jpg',
    title:
      'Bacca Bucci Essential Your Everyday All Purpose Walking Running Casual Shoes',
    currentPrice: 1099,
    originalPrice: 2499,
    priceHistory: [],
    highestPrice: 2499,
    lowestPrice: 1099,
    averagePrice: 1099,
    discountRate: 56,
    description:
      '6.7inch Super Retina XDR display. Aluminum with color-infused glass back. Ring/Silent switch Dynamic Island. A magical way to interact with iPhone. A16 Bionic chip with 5-core GPU Advanced dual-camera system. 48MP Main | Ultra Wide. Super-high-resolution photos (24MP and 48MP). Next-generation portraits with Focus and Depth Control. 4X optical zoom range Emergency SOS via satellite. Crash Detection. Roadside Assistance via satellite Up to 26 hours video playback. USB C, Supports USB 2. Face ID',
    category: 'Shoes',
    reviewsCount: 175,
    stars: 3.9,
    isOutOfStock: false
  },
  {
    _id: '5',
    url: 'https://www.amazon.in/Bacca-Bucci-Essential-Everyday-Purpose/dp/B0C3XVB8GK',
    currency: '₹',
    image: 'https://m.media-amazon.com/images/I/71fn1hHssYL._SL1500_.jpg',
    title:
      'Bacca Bucci Essential Your Everyday All Purpose Walking Running Casual Shoes',
    currentPrice: 1099,
    originalPrice: 2499,
    priceHistory: [],
    highestPrice: 2499,
    lowestPrice: 1099,
    averagePrice: 1099,
    discountRate: 56,
    description:
      '6.7inch Super Retina XDR display. Aluminum with color-infused glass back. Ring/Silent switch Dynamic Island. A magical way to interact with iPhone. A16 Bionic chip with 5-core GPU Advanced dual-camera system. 48MP Main | Ultra Wide. Super-high-resolution photos (24MP and 48MP). Next-generation portraits with Focus and Depth Control. 4X optical zoom range Emergency SOS via satellite. Crash Detection. Roadside Assistance via satellite Up to 26 hours video playback. USB C, Supports USB 2. Face ID',
    category: 'Cell Phones & Accessories',
    reviewsCount: 175,
    stars: 3.9,
    isOutOfStock: false
  },
  {
    _id: '6',
    url: 'https://www.amazon.com/Quencher-FlowState-Stainless-Insulated-Smoothie/dp/B0CJZMP7L1',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/51zaCVh6SIL._AC_SY879_.jpg',
    title:
      'Stanley Quencher H2.0 FlowState Stainless Steel Vacuum Insulated Tumbler with Lid and Straw for Water, Iced Tea or Coffee',
    currentPrice: 35,
    originalPrice: 35,
    priceHistory: [],
    highestPrice: 60,
    lowestPrice: 35,
    averagePrice: 35,
    discountRate: 0,
    description:
      "Constructed of recycled stainless steel for sustainable sipping, our Quencher H2.0 offers maximum hydration with fewer refills. Commuting, studio workouts, day trips, or your front porch–you'll want this tumbler by your side.",
    category: 'Tumblers & Water Glasses',
    reviewsCount: 50352,
    stars: 4.6,
    isOutOfStock: false,
    users: []
  },
  {
    _id: '7',
    url: 'https://www.amazon.com/OneOdio-PRO1030-DJ-Headphone-Black/dp/B01N6ZJH96',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/810x8VKZbyL._AC_SY355_.jpg',
    title: 'OneOdio Wired Over Ear Headphones Studio Monitor',
    currentPrice: 31.99,
    originalPrice: 37.99,
    priceHistory: [],
    highestPrice: 37.99,
    lowestPrice: 19.99,
    averagePrice: 31.99,
    discountRate: 16.67,
    description:
      'Enjoy clear sound and comfort with the OneOdio Studio monitor headphones. Large, 50 millimeter speaker unit drivers combined with neodymium magnets; powerful bass, clear vocal, and crisp high tones form stereo sound.',
    category: 'Headphones',
    reviewsCount: 70903,
    stars: 4.4,
    isOutOfStock: false,
    users: []
  },
  {
    _id: '8',
    url: 'https://www.amazon.com/INIU-High-Speed-Flashlight-Powerbank-Compatible/dp/B07CZDXDG8/ref=zg_bs_c_wireless_d_sccl_9/138-1372279-9483861?pd_rd_w=Lnrdp&content-id=amzn1.sym.309d45c5-3eba-4f62-9bb2-0acdcf0662e7&pf_rd_p=309d45c5-3eba-4f62-9bb2-0acdcf0662e7&pf_rd_r=4FQW1Z5J0DB295MB0GYY&pd_rd_wg=7KKIa&pd_rd_r=b9fdc619-3177-4bef-8de7-8532d51509cf&pd_rd_i=B07CZDXDG8&th=1',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/516tnauVb+L._AC_SY450_.jpg',
    title:
      'INIU Portable Charger, Slimmest 10000mAh 5V/3A Power Bank, USB C in&out High-Speed Charging Battery Pack, External Phone Powerbank Compatible with iPhone 15 14 13 12 11 Samsung S22 S21 Google iPad etc',
    currentPrice: 19.99,
    originalPrice: 29.99,
    priceHistory: [],
    highestPrice: 37.99,
    lowestPrice: 13.39,
    averagePrice: 29.99,
    discountRate: 33,
    description:
      'The Safe Choice for Charging. Our chargers are designed to meet the highest safety standards, each backed by the industry-leading 3-year refresh care. So you can have peace of mind knowing that your devices are always in good hands.',
    category: 'Portable Power Banks',
    reviewsCount: 92094,
    recommendation: 79,
    stars: 4.6,
    isOutOfStock: false,
    users: []
  },
  {
    _id: '9',
    url: 'https://www.amazon.com/Apple-20W-USB-C-Power-Adapter/dp/B08L5M9BTJ/ref=zg_bs_c_wireless_d_sccl_3/138-1372279-9483861?pd_rd_w=Lnrdp&content-id=amzn1.sym.309d45c5-3eba-4f62-9bb2-0acdcf0662e7&pf_rd_p=309d45c5-3eba-4f62-9bb2-0acdcf0662e7&pf_rd_r=4FQW1Z5J0DB295MB0GYY&pd_rd_wg=7KKIa&pd_rd_r=b9fdc619-3177-4bef-8de7-8532d51509cf&pd_rd_i=B08L5M9BTJ&psc=1',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/41iWogJnZQL._AC_SX342_.jpg',
    title: 'Apple 20W USB-C Power Adapter',
    currentPrice: 14.99,
    originalPrice: 19,
    priceHistory: [],
    highestPrice: 29,
    lowestPrice: 14.99,
    averagePrice: 14.99,
    discountRate: 21,
    description:
      'The Apple 20W USB‑C Power Adapter offers fast, efficient charging at home, in the office, or on the go. While the power adapter is compatible with any USB‑C-enabled device, Apple recommends pairing it with the 11-inch iPad Pro and 12.9-inch iPad Pro (3rd generation) for optimal charging performance. You can also pair it with iPhone 8 or later to take advantage of the fast-charging feature.',
    category: 'Cell Phone Wall Chargers',
    reviewsCount: 70903,
    stars: 4.8,
    isOutOfStock: false
  },
  {
    _id: '10',
    url: 'https://www.amazon.com/fire-tv-stick-with-3rd-gen-alexa-voice-remote/dp/B08C1W5N87/ref=zg_bs_c_amazon-devices_d_sccl_2/138-1372279-9483861?pd_rd_w=IHLB8&content-id=amzn1.sym.309d45c5-3eba-4f62-9bb2-0acdcf0662e7&pf_rd_p=309d45c5-3eba-4f62-9bb2-0acdcf0662e7&pf_rd_r=4FQW1Z5J0DB295MB0GYY&pd_rd_wg=7KKIa&pd_rd_r=b9fdc619-3177-4bef-8de7-8532d51509cf&pd_rd_i=B08C1W5N87&psc=1',
    currency: '$',
    image: 'https://m.media-amazon.com/images/I/51TjJOTfslL._AC_SY355_.jpg',
    title:
      'Amazon Fire TV Stick, HD, sharp picture quality, fast streaming, free & live TV, Alexa Voice Remote with TV controls',
    currentPrice: 39.99,
    originalPrice: 39.99,
    priceHistory: [],
    highestPrice: 39.99,
    lowestPrice: 31.99,
    averagePrice: 35.99,
    discountRate: 0,
    description:
      '50% more powerful streaming, plus convenient TV controls Fire TV Stick simplifies streaming with power, volume, and mute buttons in a single remote. And with 50% more power than the previous generation, Fire TV Stick delivers quick app starts and fast streaming in Full HD.',
    category: 'Streaming Media Players',
    reviewsCount: 453089,
    stars: 4.8,
    isOutOfStock: false
  }
]
